#import your models here

from .bodega import Bodega
from .comuna import Comuna
from .condicionpago import CondicionPago
from .contacto import Contacto
from .direccion import Direccion
from .documento import Documento
from .gruposn import GrupoSN
from .inventario import Inventario
from .item import Item
from .producto import Producto
from .region import Region
from .socionegocio import SocioNegocio
from .sucursal import Sucursal
from .tipocliente import TipoCliente
from .tipodoctributario import TipoDocTributario
from .tipoentrega import TipoEntrega
from .tipoobjetosap import TipoObjetoSap
from .tiposn import TipoSN
from .tipotelefono import TipoTelefono
from .tipoventa import TipoVenta
from .usuario import Usuario
from .vendedor import Vendedor
