#import your models here

from datosLsApp.models.bodega import Bodega
from datosLsApp.models.comuna import Comuna
from datosLsApp.models.condicionpago import CondicionPago
from datosLsApp.models.contacto import Contacto
from datosLsApp.models.direccion import Direccion
from datosLsApp.models.documento import Documento
from datosLsApp.models.gruposn import GrupoSN
from datosLsApp.models.inventario import Inventario
from datosLsApp.models.item import Item
from datosLsApp.models.producto import Producto
from datosLsApp.models.region import Region
from datosLsApp.models.socionegocio import SocioNegocio
from datosLsApp.models.sucursal import Sucursal
from datosLsApp.models.tipocliente import TipoCliente
from datosLsApp.models.tipodoctributario import TipoDocTributario
from datosLsApp.models.tipoentrega import TipoEntrega
from datosLsApp.models.tipoobjetosap import TipoObjetoSap
from datosLsApp.models.tiposn import TipoSN
from datosLsApp.models.tipotelefono import TipoTelefono
from datosLsApp.models.tipoventa import TipoVenta
from datosLsApp.models.usuario import Usuario
from datosLsApp.models.vendedor import Vendedor
