#import your models here

from datosLsApp.models.bodegadb import BodegaDB
from datosLsApp.models.comunadb import ComunaDB
from datosLsApp.models.condicionpagodb import CondicionPagoDB
from datosLsApp.models.contactodb import ContactoDB
from datosLsApp.models.direcciondb import DireccionDB
from datosLsApp.models.documentodb import DocumentoDB
from datosLsApp.models.gruposndb import GrupoSNDB
from datosLsApp.models.inventariodb import InventarioDB
from datosLsApp.models.lineadb import LineaDB
from datosLsApp.models.productodb import ProductoDB
from datosLsApp.models.regiondb import RegionDB
from datosLsApp.models.socionegociodb import SocioNegocioDB
from datosLsApp.models.sucursaldb import SucursalDB
from datosLsApp.models.tipoclientedb import TipoClienteDB
from datosLsApp.models.tipodoctributariodb import TipoDocTributarioDB
from datosLsApp.models.tipoentregadb import TipoEntregaDB
from datosLsApp.models.tipoobjetosapdb import TipoObjetoSapDB
from datosLsApp.models.tiposndb import TipoSNDB
from datosLsApp.models.tipotelefonodb import TipoTelefonoDB
from datosLsApp.models.tipoventadb import TipoVentaDB
from datosLsApp.models.usuariodb import UsuarioDB
from datosLsApp.models.vendedordb import VendedorDB
from datosLsApp.models.stockbodegasdb import StockBodegasDB
from datosLsApp.models.collectionsdb import CollectionsDB
from datosLsApp.models.rules_coupondb import RulesCouponDB