# Generated by Django 4.2.6 on 2024-04-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='ciudad',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='rowNum',
            field=models.IntegerField(default='0 '),
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='tipoDireccion',
        ),
        migrations.DeleteModel(
            name='TipoDireccion',
        ),
        migrations.AddField(
            model_name='direccion',
            name='tipoDireccion',
            field=models.CharField(default='NA', max_length=5),
        ),
    ]
