# Generated by Django 5.0.1 on 2024-02-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gruposn',
            name='codigo',
            field=models.IntegerField(max_length=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipocliente',
            name='codigo',
            field=models.CharField(max_length=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tiposn',
            name='codigo',
            field=models.CharField(max_length=1, primary_key=True, serialize=False),
        ),
    ]
