# Generated by Django 5.0.1 on 2024-02-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0002_alter_gruposn_codigo_alter_tipocliente_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gruposn',
            name='codigo',
            field=models.CharField(max_length=1, primary_key=True, serialize=False),
        ),
    ]
