# Generated by Django 4.2.6 on 2023-10-31 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0002_rename_cometario_documento_comentario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='vendedor',
        ),
        migrations.AddField(
            model_name='documento',
            name='vendedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestionPedidos.vendedor'),
        ),
    ]
