# Generated by Django 4.2.6 on 2023-10-31 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0003_remove_documento_vendedor_documento_vendedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendedor',
            name='tipo_sucursal',
        ),
        migrations.AddField(
            model_name='vendedor',
            name='sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestionPedidos.sucursal'),
        ),
    ]
