# Generated by Django 5.0.1 on 2024-02-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0003_alter_gruposn_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gruposn',
            name='codigo',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
