# Generated by Django 4.2.6 on 2023-10-31 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0004_remove_vendedor_tipo_sucursal_vendedor_sucursal'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='documento',
            name='condi_pago',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestionPedidos.condicionpago'),
        ),
    ]
