# Generated by Django 5.0.1 on 2024-02-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0004_alter_gruposn_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipodireccion',
            name='id',
        ),
        migrations.AlterField(
            model_name='tipodireccion',
            name='codigo',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
