# Generated by Django 4.2.6 on 2023-10-31 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0005_condicionpago_documento_condi_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('imagen', models.CharField(max_length=50)),
                ('stockTotal', models.IntegerField()),
                ('precioLista', models.FloatField()),
                ('precioVenta', models.FloatField()),
                ('dsctoMaxTienda', models.FloatField()),
                ('dctoMaxProyectos', models.FloatField()),
                ('linkProducto', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numLinea', models.IntegerField()),
                ('descuento', models.FloatField(default=0)),
                ('cantidad', models.IntegerField()),
                ('totalNetoLinea', models.FloatField()),
                ('totalBrutoLinea', models.FloatField()),
                ('comentario', models.CharField(max_length=255)),
                ('tipoObjetoDocBase', models.CharField(max_length=255)),
                ('docEntryBase', models.IntegerField()),
                ('numLineaBase', models.IntegerField()),
                ('fechaEntrega', models.DateField()),
                ('direccionEntrega', models.CharField(max_length=255)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionPedidos.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodega', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestionPedidos.bodega')),
                ('producto', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestionPedidos.producto')),
            ],
        ),
    ]
