# Generated by Django 4.2.6 on 2023-10-31 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0006_bodega_producto_item_inventario'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tipodoctributario',
            table='Tipo_Documento',
        ),
    ]
