# Generated by Django 4.2.6 on 2023-10-31 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0007_alter_tipodoctributario_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('tipo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoObjetoSap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='documento',
            options={},
        ),
        migrations.AddField(
            model_name='item',
            name='documento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestionPedidos.documento'),
        ),
        migrations.AddField(
            model_name='documento',
            name='tipoentrega',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestionPedidos.tipoentrega'),
        ),
        migrations.AddField(
            model_name='documento',
            name='tipoobjetoSap',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestionPedidos.tipoobjetosap'),
        ),
        migrations.AddField(
            model_name='item',
            name='tipoentrega',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestionPedidos.tipoentrega'),
        ),
        migrations.AddField(
            model_name='item',
            name='tipoobjetoSap',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestionPedidos.tipoobjetosap'),
        ),
    ]
