# Generated by Django 4.2.6 on 2023-10-31 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0008_tipoentrega_tipoobjetosap_alter_documento_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bodega',
            table='Bodega',
        ),
        migrations.AlterModelTable(
            name='condicionpago',
            table='CondicionPago',
        ),
        migrations.AlterModelTable(
            name='documento',
            table='Documento',
        ),
        migrations.AlterModelTable(
            name='inventario',
            table='Inventario',
        ),
        migrations.AlterModelTable(
            name='item',
            table='Item',
        ),
        migrations.AlterModelTable(
            name='producto',
            table='Producto',
        ),
        migrations.AlterModelTable(
            name='sucursal',
            table='Sucursal',
        ),
        migrations.AlterModelTable(
            name='tipodoctributario',
            table='TipoDocTributario',
        ),
        migrations.AlterModelTable(
            name='tipoentrega',
            table='TipoEntrega',
        ),
        migrations.AlterModelTable(
            name='tipoobjetosap',
            table='TipoObjetoSap',
        ),
        migrations.AlterModelTable(
            name='tipoventa',
            table='TipoVenta',
        ),
        migrations.AlterModelTable(
            name='vendedor',
            table='Vendedor',
        ),
    ]
