# Generated by Django 4.2.6 on 2023-11-08 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0009_alter_bodega_table_alter_condicionpago_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoInternoSap', models.IntegerField()),
                ('nombreCompleto', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=10)),
                ('celular', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Direccion',
                'verbose_name_plural': 'Direccion',
                'db_table': 'Contacto',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Pais',
                'db_table': 'Pais',
            },
        ),
        migrations.CreateModel(
            name='TipoDireccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'TipoDireccion',
                'verbose_name_plural': 'TipoDireccion',
                'db_table': 'TipoDireccion',
            },
        ),
        migrations.CreateModel(
            name='TipoTelefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'TipoDireccion',
                'verbose_name_plural': 'TipoDireccion',
                'db_table': 'TipoTelefono',
            },
        ),
        migrations.AlterModelOptions(
            name='tipodoctributario',
            options={'verbose_name': 'TipoDocTributario', 'verbose_name_plural': 'TipoDocTributario'},
        ),
        migrations.CreateModel(
            name='TipoSN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('contacto', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestionPedidos.contacto')),
            ],
        ),
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('contacto', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestionPedidos.contacto')),
            ],
        ),
        migrations.CreateModel(
            name='SocioNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('razonSocial', models.CharField(max_length=255)),
                ('codigoSN', models.CharField(max_length=255)),
                ('rut', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=10)),
                ('giro', models.CharField(max_length=50)),
                ('alias', models.CharField(max_length=55)),
                ('condicionPago', models.IntegerField(default=-1)),
                ('plazoReclamaciones', models.CharField(default='STANDAR', max_length=255)),
                ('clienteExportacion', models.CharField(default='N', max_length=255)),
                ('vendedor', models.IntegerField(default=-1)),
                ('tipotelefono', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestionPedidos.tipotelefono')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('pais', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestionPedidos.pais')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Region',
                'db_table': 'Region',
            },
        ),
        migrations.CreateModel(
            name='GrupoSN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('contacto', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestionPedidos.contacto')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rowNum', models.IntegerField()),
                ('nombreDireccion', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('comuna', models.CharField(max_length=50)),
                ('calleNumero', models.CharField(max_length=50)),
                ('codigoImpuesto', models.CharField(default='iva', max_length=100)),
                ('tipoDireccion', models.ManyToManyField(related_name='tipodedirecciones', to='gestionPedidos.tipodireccion')),
            ],
            options={
                'verbose_name': 'Direccion',
                'verbose_name_plural': 'Direccion',
                'db_table': 'Direccion',
            },
        ),
        migrations.AddField(
            model_name='contacto',
            name='tipoDireccion',
            field=models.ManyToManyField(related_name='SociosNegocio', to='gestionPedidos.socionegocio'),
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('region', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestionPedidos.region')),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comuna',
                'db_table': 'Comuna',
            },
        ),
    ]
