# Generated by Django 4.2.6 on 2023-11-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0010_contacto_pais_tipodireccion_tipotelefono_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('shirt_sizes', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='direccion',
            name='tipoDireccion',
            field=models.ManyToManyField(related_name='directorios', to='gestionPedidos.tipodireccion'),
        ),
    ]
