# Generated by Django 4.2.6 on 2024-01-17 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0013_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuario',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Usuario_Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('usuarios', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestionPedidos.usuario')),
            ],
            options={
                'verbose_name': 'usuario_login',
                'verbose_name_plural': 'usuario_login',
                'db_table': 'usuario_login',
            },
        ),
    ]
