# Generated by Django 4.2.6 on 2024-01-25 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0015_usuario_usuarios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario_Login',
        ),
    ]
