# Generated by Django 4.2.6 on 2024-01-25 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0016_delete_usuario_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prueba',
        ),
    ]
