# Generated by Django 4.2.6 on 2024-01-25 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0017_delete_prueba'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articulos',
        ),
        migrations.DeleteModel(
            name='Pedidos',
        ),
    ]
