# Generated by Django 4.2.6 on 2024-01-25 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0018_delete_articulos_delete_pedidos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Item'},
        ),
        migrations.AlterModelTable(
            name='item',
            table='item',
        ),
    ]
