# Generated by Django 4.2.6 on 2024-01-25 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0019_alter_item_options_alter_item_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodega',
            options={'verbose_name': 'Bodega', 'verbose_name_plural': 'Bodega'},
        ),
        migrations.AlterModelTable(
            name='bodega',
            table='bodega',
        ),
    ]
