# Generated by Django 4.2.6 on 2024-02-07 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestionPedidos', '0020_alter_bodega_options_alter_bodega_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='usuarios',
        ),
        migrations.AddField(
            model_name='usuario',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
