# Generated by Django 5.0.1 on 2024-02-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0020_alter_bodega_options_alter_bodega_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stockTotal',
            field=models.IntegerField(default=0),
        ),
    ]
