# Generated by Django 5.0.1 on 2024-02-08 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0035_alter_usuario_usuarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='usuarios',
        ),
    ]
