# Generated by Django 4.2.6 on 2024-02-08 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0022_remove_usuario_user_usuario_usuarios'),
        ('gestionPedidos', '0038_alter_usuario_usuarios'),
    ]

    operations = [
    ]
