# Generated by Django 4.2.6 on 2024-02-12 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0039_alter_documento_options_alter_sucursal_options_and_more'),
        ('gestionPedidos', '0040_alter_usuario_usuarios'),
    ]

    operations = [
    ]
