# Generated by Django 5.1.8 on 2025-05-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentLogDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docNum', models.IntegerField(null=True)),
                ('docEntry', models.IntegerField(null=True)),
                ('tipoDoc', models.CharField(max_length=20, null=True)),
                ('url', models.CharField(max_length=255, null=True)),
                ('json', models.TextField(null=True)),
                ('response', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estate', models.CharField(max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'documentLog',
                'verbose_name_plural': 'documentLog',
                'db_table': 'documentLog',
            },
        ),
    ]
